/** TenderStep – 10 sản phẩm · ảnh 1.jpg – 10.jpg */
window.TenderStepProducts = [
  {
    id: "retail-39",
    slug: "1-doi-uu-dai-39000",
    name: "Tất ủ gót chân – 1 đôi (Ưu đãi)",
    shortName: "1 đôi · Ưu đãi",
    tagline: "39.000đ – TikTok Shop, Shopee",
    image: "2.jpg",
    gallery: ["2.jpg", "3.jpg", "1.jpg"],
    price: 39000,
    oldPrice: 59000,
    priceNote: "Giá lẻ: 39.000 – 59.000đ / đôi",
    badge: "TikTok · Shopee",
    category: "retail",
    stock: 200,
    rating: 4.9,
    reviews: 412,
    description: "Tất ủ nha đam – giá ưu đãi cho khách mua thử lần đầu.",
    highlights: ["Cấp ẩm gót chân", "Ủ 20–30 phút", "Dùng tại nhà", "1 đôi (2 chiếc)"],
    ingredients: ["Nha đam", "Glycerin", "Vitamin E", "Urea", "Shea Butter"],
    howToUse: ["Rửa chân sạch", "Mang tất ủ", "Thư giãn 20–30 phút", "Massage nhẹ"],
    variants: [{ id: "retail-39", label: "1 đôi", price: 39000 }],
  },
  {
    id: "retail-49",
    slug: "1-doi-tieu-chuan-49000",
    name: "Tất ủ gót chân – 1 đôi (Tiêu chuẩn)",
    shortName: "1 đôi · Tiêu chuẩn",
    tagline: "49.000đ – Bán chạy nhất",
    image: "1.jpg",
    gallery: ["1.jpg", "7.jpg", "8.jpg"],
    price: 49000,
    oldPrice: 59000,
    priceNote: "Giá lẻ: 39.000 – 59.000đ / đôi",
    badge: "Bán chạy",
    category: "retail",
    stock: 150,
    rating: 4.9,
    reviews: 528,
    description: "Phiên bản tiêu chuẩn – cân bằng giá và chất lượng.",
    highlights: ["Vải mềm co giãn", "Ủ kín vùng gót", "Mùi nhẹ dễ chịu", "Made in Korea"],
    ingredients: ["Aloe Vera", "Glycerin", "Vitamin E", "Urea", "Shea Butter"],
    howToUse: ["Dùng 2–3 lần/tuần", "Ủ 20–30 phút", "Kết hợp kem gót nếu cần"],
    variants: [{ id: "retail-49", label: "1 đôi", price: 49000 }],
  },
  {
    id: "retail-59",
    slug: "1-doi-gel-duong-sau-59000",
    name: "Tất ủ gel dưỡng sâu – 1 đôi",
    shortName: "1 đôi · Gel sâu",
    tagline: "59.000đ – Da chai sần",
    image: "6.jpg",
    gallery: ["6.jpg", "5.jpg", "4.jpg"],
    price: 59000,
    oldPrice: 69000,
    priceNote: "Giá lẻ: 39.000 – 59.000đ / đôi",
    badge: "Chuyên sâu",
    category: "retail",
    stock: 88,
    rating: 4.8,
    reviews: 186,
    description: "Pad gel dưỡng sâu – hỗ trợ da chai sần, khô nặng.",
    highlights: ["Pad gel vùng gót", "Urea + Shea", "Cảm giác mát", "Spa tại nhà"],
    ingredients: ["Aloe Vera", "Urea", "Shea Butter", "Vitamin E"],
    howToUse: ["Ưu tiên buổi tối", "Ủ 25–35 phút", "Massage sau khi tháo"],
    variants: [{ id: "retail-59", label: "1 đôi", price: 59000 }],
  },
  {
    id: "retail-wear",
    slug: "1-doi-de-mang",
    name: "Tất ủ – Đeo thoải mái",
    shortName: "1 đôi · Đeo mẫu",
    tagline: "49.000đ – Thiết kế hở gót",
    image: "4.jpg",
    gallery: ["4.jpg", "1.jpg", "6.jpg"],
    price: 49000,
    oldPrice: 59000,
    priceNote: "Giá lẻ: 39.000 – 59.000đ / đôi",
    badge: "Mới",
    category: "retail",
    stock: 95,
    rating: 4.8,
    reviews: 74,
    description: "Thiết kế hở gót thoáng – gel tiếp xúc trực tiếp da gót chân.",
    highlights: ["Thoáng khí", "Dễ đi lại khi ủ", "Ôm sát gót", "Màu sage dịu"],
    ingredients: ["Nha đam", "Glycerin", "Vitamin E"],
    howToUse: ["Mang tất", "Ủ 20–30 phút", "Tháo và massage"],
    variants: [{ id: "retail-wear", label: "1 đôi", price: 49000 }],
  },
  {
    id: "retail-texture",
    slug: "1-doi-chat-lieu-mem",
    name: "Tất ủ – Chất liệu mềm mại",
    shortName: "1 đôi · Vải mềm",
    tagline: "52.000đ – Cảm giác êm",
    image: "5.jpg",
    gallery: ["5.jpg", "6.jpg", "10.jpg"],
    price: 52000,
    oldPrice: 62000,
    priceNote: "Giá lẻ: 39.000 – 59.000đ / đôi",
    badge: "Premium",
    category: "retail",
    stock: 70,
    rating: 4.9,
    reviews: 56,
    description: "Vải len mềm, lớp pad dưỡng dày – êm ái khi ủ.",
    highlights: ["Vải mềm", "Pad dưỡng dày", "Khâu chắc", "Dễ chịu"],
    ingredients: ["Shea Butter", "Urea", "Aloe Vera"],
    howToUse: ["Ủ buổi tối", "20–30 phút", "Giữ ẩm sau ủ"],
    variants: [{ id: "retail-texture", label: "1 đôi", price: 52000 }],
  },
  {
    id: "combo-3-sale",
    slug: "combo-3-doi-99k",
    name: "Combo 3 đôi – Khuyến mãi 99K",
    shortName: "Combo ×3 · KM",
    tagline: "99.000đ – Giá tốt nhất",
    image: "3.jpg",
    gallery: ["3.jpg", "2.jpg", "9.jpg"],
    price: 99000,
    oldPrice: 129000,
    priceNote: "Combo 3 đôi: 99.000 – 129.000đ",
    badge: "Hot deal",
    category: "combo",
    stock: 35,
    rating: 4.9,
    reviews: 121,
    description: "Combo 3 đôi giá 99K – freeship, phù hợp mua nhanh.",
    highlights: ["~33K/đôi", "Freeship", "Hàng chính hãng", "Số lượng có hạn"],
    ingredients: ["Công thức Nha đam TenderStep"],
    howToUse: ["Luân phiên 3 đôi", "Ủ 20–30 phút", "2–3 lần/tuần"],
    variants: [{ id: "combo-3-sale", label: "3 đôi", price: 99000 }],
  },
  {
    id: "combo-3",
    slug: "combo-3-doi",
    name: "Combo 3 đôi – Tiết kiệm",
    shortName: "Combo ×3",
    tagline: "114.000đ · ~38K/đôi",
    image: "8.jpg",
    gallery: ["8.jpg", "3.jpg", "1.jpg"],
    price: 114000,
    oldPrice: 129000,
    priceNote: "Combo 3 đôi: 99.000 – 129.000đ",
    badge: "Combo",
    category: "combo",
    stock: 60,
    rating: 4.9,
    reviews: 94,
    description: "Gói 3 đôi – tiết kiệm hơn mua lẻ.",
    highlights: ["Tiết kiệm 22%", "Freeship từ 99K", "Đủ dùng cả tháng", "Quà tặng"],
    ingredients: ["Nha đam TenderStep"],
    howToUse: ["Luân phiên", "Bảo quản khô ráo", "Ủ 20–30 phút"],
    variants: [{ id: "combo-3", label: "3 đôi", price: 114000 }],
  },
  {
    id: "combo-5",
    slug: "combo-5-doi",
    name: "Combo 5 đôi – Gia đình",
    shortName: "Combo ×5",
    tagline: "179.000đ · ~36K/đôi",
    image: "7.jpg",
    gallery: ["7.jpg", "8.jpg", "1.jpg"],
    price: 179000,
    oldPrice: 199000,
    priceNote: "Combo 5 đôi: 159.000 – 199.000đ",
    badge: "Tiết kiệm nhất",
    category: "combo",
    stock: 40,
    rating: 5,
    reviews: 67,
    description: "Combo 5 đôi – tối ưu cho gia đình, nhóm bạn.",
    highlights: ["Giá/đôi thấp nhất", "Freeship", "Chia dùng", "Voucher KM"],
    ingredients: ["Nha đam TenderStep"],
    howToUse: ["Chia theo tuần", "Tặng từng đôi", "Ủ 20–30 phút"],
    variants: [{ id: "combo-5", label: "5 đôi", price: 179000 }],
  },
  {
    id: "retail-spa",
    slug: "1-doi-spa-tai-nha",
    name: "Tất ủ Spa tại nhà",
    shortName: "1 đôi · Spa",
    tagline: "49.000đ – Thư giãn",
    image: "9.jpg",
    gallery: ["9.jpg", "2.jpg", "3.jpg"],
    price: 49000,
    oldPrice: 59000,
    priceNote: "Giá lẻ: 39.000 – 59.000đ / đôi",
    badge: "Yêu thích",
    category: "retail",
    stock: 110,
    rating: 4.9,
    reviews: 203,
    description: "Trải nghiệm spa nhẹ tại nhà – nha đam & khăn mềm.",
    highlights: ["Thư giãn", "Mùi dịu", "Dễ dùng", "Quà tặng"],
    ingredients: ["Aloe Vera", "Glycerin", "Vitamin E"],
    howToUse: ["Buổi tối cuối tuần", "Ủ 25 phút", "Thư giãn hoàn toàn"],
    variants: [{ id: "retail-spa", label: "1 đôi", price: 49000 }],
  },
  {
    id: "retail-flex",
    slug: "1-doi-co-gian",
    name: "Tất ủ – Co giãn tốt",
    shortName: "1 đôi · Co giãn",
    tagline: "45.000đ – Ôm vừa vặn",
    image: "10.jpg",
    gallery: ["10.jpg", "5.jpg", "2.jpg"],
    price: 45000,
    oldPrice: 55000,
    priceNote: "Giá lẻ: 39.000 – 59.000đ / đôi",
    badge: "Linh hoạt",
    category: "retail",
    stock: 130,
    rating: 4.7,
    reviews: 89,
    description: "Co giãn tốt – phù hợp mọi cỡ chân, dễ mang.",
    highlights: ["Co giãn", "Ôm vừa", "Không chật", "Bền đẹp"],
    ingredients: ["Aloe Vera", "Glycerin", "Urea"],
    howToUse: ["Kéo nhẹ khi mang", "Ủ 20–30 phút", "Không kéo mạnh"],
    variants: [{ id: "retail-flex", label: "1 đôi", price: 45000 }],
  },
];

window.TenderStepStore = {
  formatPrice(n) {
    return new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND" }).format(n);
  },

  imgSrc(file) {
    return "images/" + file;
  },

  getProduct(id) {
    return window.TenderStepProducts.find((p) => p.id === id);
  },

  getProductBySlug(slug) {
    return window.TenderStepProducts.find((p) => p.slug === slug);
  },
};
